In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd

path = "/content/drive/MyDrive/banking-ai-knowledge-system/dataset/train.csv"

df = pd.read_csv(path)

df.head()

                                                text      category
0                     I am still waiting on my card?  card_arrival
1  What can I do if my card still hasn't arrived ...  card_arrival
2  I have been waiting over a week. Is the card s...  card_arrival
3  Can I track my card while it is in the process...  card_arrival
4  How do I know if I will get my card, or if it ...  card_arrival

In [3]:
df.shape

(10003, 2)

In [4]:
df.columns

Index(['text', 'category'], dtype='object')

In [5]:
df["category"].nunique()

KeyError: 'label'

In [6]:
df['category'].nunique()

77

In [7]:
df["category"].unique()

array(['card_arrival', 'card_linking', 'exchange_rate',
       'card_payment_wrong_exchange_rate', 'extra_charge_on_statement',
       'pending_cash_withdrawal', 'fiat_currency_support',
       'card_delivery_estimate', 'automatic_top_up', 'card_not_working',
       'exchange_via_app', 'lost_or_stolen_card', 'age_limit',
       'pin_blocked', 'contactless_not_working',
       'top_up_by_bank_transfer_charge', 'pending_top_up',
       'cancel_transfer', 'top_up_limits',
       'wrong_amount_of_cash_received', 'card_payment_fee_charged',
       'transfer_not_received_by_recipient',
       'supported_cards_and_currencies', 'getting_virtual_card',
       'card_acceptance', 'top_up_reverted',
       'balance_not_updated_after_cheque_or_cash_deposit',
       'card_payment_not_recognised', 'edit_personal_details',
       'why_verify_identity', 'unable_to_verify_identity',
       'get_physical_card', 'visa_or_mastercard', 'topping_up_by_card',
       'disposable_card_limits', 'compromised_card', 'atm_support',
       'direct_debit_payment_not_recognised', 'passcode_forgotten',
       'declined_cash_withdrawal', 'pending_card_payment',
       'lost_or_stolen_phone', 'request_refund', 'declined_transfer',
       'Refund_not_showing_up', 'declined_card_payment',
       'pending_transfer', 'terminate_account', 'card_swallowed',
       'transaction_charged_twice', 'verify_source_of_funds',
       'transfer_timing', 'reverted_card_payment?', 'change_pin',
       'beneficiary_not_allowed', 'transfer_fee_charged',
       'receiving_money', 'failed_transfer', 'transfer_into_account',
       'verify_top_up', 'getting_spare_card', 'top_up_by_cash_or_cheque',
       'order_physical_card', 'virtual_card_not_working',
       'wrong_exchange_rate_for_cash_withdrawal',
       'get_disposable_virtual_card', 'top_up_failed',
       'balance_not_updated_after_bank_transfer',
       'cash_withdrawal_not_recognised', 'exchange_charge',
       'top_up_by_card_charge', 'activate_my_card',
       'cash_withdrawal_charge', 'card_about_to_expire',
       'apple_pay_or_google_pay', 'verify_my_identity', 'country_support'],
      dtype=object)

In [8]:
df["category"].value_counts()

category
card_payment_fee_charged                            187
direct_debit_payment_not_recognised                 182
balance_not_updated_after_cheque_or_cash_deposit    181
wrong_amount_of_cash_received                       180
cash_withdrawal_charge                              177
                                                   ...
lost_or_stolen_card                                  82
card_swallowed                                       61
card_acceptance                                      59
virtual_card_not_working                             41
contactless_not_working                              35
Name: count, Length: 77, dtype: int64

In [9]:
df.isnull().sum()

text        0
category    0
dtype: int64

In [10]:
df.head()

                                                text      category
0                     I am still waiting on my card?  card_arrival
1  What can I do if my card still hasn't arrived ...  card_arrival
2  I have been waiting over a week. Is the card s...  card_arrival
3  Can I track my card while it is in the process...  card_arrival
4  How do I know if I will get my card, or if it ...  card_arrival

In [11]:
output_path = "/content/drive/MyDrive/banking-ai-knowledge-system/dataset/banking_queries.csv"

df.to_csv(output_path, index=False)

print("Clean dataset saved")

Clean dataset saved