In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
import pandas as pd
import numpy as np

import nltk
import re

from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report

In [3]:
path = "/content/drive/MyDrive/banking-ai-knowledge-system/dataset/banking_queries.csv"

df = pd.read_csv(path)

df.head()

                                                text      category
0                     I am still waiting on my card?  card_arrival
1  What can I do if my card still hasn't arrived ...  card_arrival
2  I have been waiting over a week. Is the card s...  card_arrival
3  Can I track my card while it is in the process...  card_arrival
4  How do I know if I will get my card, or if it ...  card_arrival

In [4]:
print("Dataset size:", df.shape)
print("Number of intents:", df["category"].nunique())

Dataset size: (10003, 2)

KeyError: 'intent'

In [5]:
print("Dataset size:", df.shape)
print("Number of category:", df["category"].nunique())

Dataset size: (10003, 2)
Number of category: 77

In [6]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.

True

In [7]:
from nltk.corpus import stopwords

stop_words = set(stopwords.words("english"))

In [8]:
def clean_text(text):

    text = text.lower()

    text = re.sub(r"[^\w\s]", "", text)

    words = text.split()

    words = [w for w in words if w not in stop_words]

    return " ".join(words)

In [9]:
df["clean_query"] = df["text"].apply(clean_text)

df.head()

KeyError: 'query'

In [10]:
df["clean_text"] = df["text"].apply(clean_text)

df.head()

,text,category,clean_text
0,I am still waiting on my card?,card_arrival,still waiting card
1,What can I do if my card still hasn't arrived ...,card_arrival,card still hasnt arrived 2 weeks
2,I have been waiting over a week. Is the card s...,card_arrival,waiting week card still coming
3,Can I track my card while it is in the process...,card_arrival,track card process delivery
4,"How do I know if I will get my card, or if it ...",card_arrival,know get card lost

In [11]:
X = df["clean_text"]
y = df["category"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [12]:
vectorizer = TfidfVectorizer()

X_train_vec = vectorizer.fit_transform(X_train)
X_test_vec = vectorizer.transform(X_test)

In [13]:
model = LogisticRegression(max_iter=200)

model.fit(X_train_vec, y_train)

LogisticRegression(max_iter=200)

In [14]:
y_pred = model.predict(X_test_vec)

print(classification_report(y_test, y_pred))

                                                  precision    recall  f1-score   support

                           Refund_not_showing_up       0.88      0.94      0.91        32
                                activate_my_card       1.00      0.90      0.95        31
                                       age_limit       1.00      0.96      0.98        25
                         apple_pay_or_google_pay       1.00      1.00      1.00        23
                                     atm_support       1.00      0.84      0.91        19
                                automatic_top_up       1.00      0.96      0.98        27
         balance_not_updated_after_bank_transfer       0.78      0.81      0.79        31
balance_not_updated_after_cheque_or_cash_deposit       0.90      0.85      0.88        41
                         beneficiary_not_allowed       0.85      0.96      0.90        24
                                 cancel_transfer       0.89      0.94      0.92        35
                            card_about_to_expire       0.92      0.92      0.92        25
                                 card_acceptance       1.00      0.65      0.79        20
                                    card_arrival       0.71      0.90      0.80        39
                          card_delivery_estimate       0.76      0.64      0.70        25
                                    card_linking       0.95      0.91      0.93        22
                                card_not_working       0.73      0.83      0.78        23
                        card_payment_fee_charged       0.82      0.97      0.89        34
                     card_payment_not_recognised       0.62      0.88      0.73        26
                card_payment_wrong_exchange_rate       1.00      0.76      0.86        33
                                  card_swallowed       1.00      0.88      0.93         8
                          cash_withdrawal_charge       0.81      0.97      0.88        31
                  cash_withdrawal_not_recognised       0.77      0.88      0.82        26
                                      change_pin       1.00      0.83      0.91        24
                                compromised_card       0.89      0.73      0.80        22
                         contactless_not_working       1.00      0.78      0.88         9
                                 country_support       0.96      0.88      0.92        25
                           declined_card_payment       0.85      0.85      0.85        26
                        declined_cash_withdrawal       0.69      0.89      0.78        28
                               declined_transfer       0.94      0.94      0.94        31
             direct_debit_payment_not_recognised       1.00      0.78      0.88        37
                          disposable_card_limits       0.93      0.83      0.88        30
                           edit_personal_details       1.00      1.00      1.00        24
                                 exchange_charge       0.90      0.90      0.90        29
                                   exchange_rate       0.75      0.81      0.78        26
                                exchange_via_app       0.95      0.83      0.88        23
                       extra_charge_on_statement       0.86      0.77      0.81        39
                                 failed_transfer       0.79      0.77      0.78        30
                           fiat_currency_support       0.77      1.00      0.87        20
                     get_disposable_virtual_card       0.75      0.79      0.77        19
                               get_physical_card       0.82      0.88      0.85        26
                              getting_spare_card       0.73      0.86      0.79        22
                            getting_virtual_card       0.82      1.00      0.90        32
                             lost_or_stolen_card       0.76      0.72      0.74        18
                            lost_or_stolen_phone       0.88      0.88      0.88        16
                             order_physical_card       0.80      0.77      0.78        26
                              passcode_forgotten       0.94      0.97      0.95        30
                            pending_card_payment       0.88      0.91      0.89        32
                         pending_cash_withdrawal       0.96      0.80      0.87        30
                                  pending_top_up       0.76      0.65      0.70        20
                                pending_transfer       0.86      0.74      0.79        34
                                     pin_blocked       0.92      0.89      0.91        27
                                 receiving_money       0.92      1.00      0.96        11
                                  request_refund       0.89      0.86      0.88        29
                          reverted_card_payment?       0.81      0.85      0.83        40
                  supported_cards_and_currencies       0.89      0.80      0.84        30
                               terminate_account       0.95      0.87      0.91        23
                  top_up_by_bank_transfer_charge       0.72      0.76      0.74        17
                           top_up_by_card_charge       0.95      0.95      0.95        20
                        top_up_by_cash_or_cheque       0.95      0.88      0.91        24
                                   top_up_failed       0.69      0.81      0.75        31
                                   top_up_limits       0.94      0.85      0.89        20
                                 top_up_reverted       0.70      0.76      0.73        21
                              topping_up_by_card       0.69      0.69      0.69        16
                       transaction_charged_twice       0.95      0.89      0.92        45
                            transfer_fee_charged       0.94      0.89      0.91        36
                           transfer_into_account       0.62      0.68      0.65        19
              transfer_not_received_by_recipient       0.67      0.81      0.73        27
                                 transfer_timing       0.80      0.80      0.80        20
                       unable_to_verify_identity       0.80      0.76      0.78        21
                              verify_my_identity       0.71      0.68      0.70        22
                          verify_source_of_funds       0.82      0.92      0.87        25
                                   verify_top_up       0.93      1.00      0.96        26
                        virtual_card_not_working       1.00      0.44      0.62         9
                              visa_or_mastercard       1.00      0.96      0.98        25
                             why_verify_identity       0.55      0.55      0.55        20
                   wrong_amount_of_cash_received       0.94      0.88      0.91        34
         wrong_exchange_rate_for_cash_withdrawal       0.79      0.77      0.78        35

                                        accuracy                           0.85      2001
                                       macro avg       0.86      0.84      0.85      2001
                                    weighted avg       0.86      0.85      0.85      2001

In [15]:
def predict_intent(query):

    cleaned = clean_text(query)

    vec = vectorizer.transform([cleaned])

    pred = model.predict(vec)[0]

    return pred

In [16]:
predict_intent("My card was stolen")

'lost_or_stolen_card'

In [17]:
predict_intent("How do I activate my credit card?")

'activate_my_card'

In [18]:
!pip install joblib

Requirement already satisfied: joblib in /usr/local/lib/python3.12/dist-packages (1.5.3)

In [19]:
import joblib

model_path = "/content/drive/MyDrive/banking-ai-knowledge-system/nlp_model/intent_model.pkl"

vectorizer_path = "/content/drive/MyDrive/banking-ai-knowledge-system/nlp_model/vectorizer.pkl"

joblib.dump(model, model_path)
joblib.dump(vectorizer, vectorizer_path)

print("Model saved")

Model saved